# Generated by Django 4.2.6 on 2023-10-30 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task_tracker', '0002_task_parenttask_task_priority'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='parentTask',
        ),
        migrations.AddField(
            model_name='task',
            name='parent_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='task_tracker.task'),
        ),
    ]
