# Generated by Django 4.2.6 on 2023-11-16 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_tracker', '0003_remove_task_parenttask_task_parent_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=1000)),
            ],
        ),
        migrations.RemoveField(
            model_name='task',
            name='department',
        ),
        migrations.AddField(
            model_name='task',
            name='department',
            field=models.ManyToManyField(blank=True, related_name='tasks', to='task_tracker.department'),
        ),
    ]
