# Generated by Django 4.2.6 on 2023-11-16 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_tracker', '0004_department_remove_task_department_task_department'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='department',
            new_name='departments',
        ),
    ]
