# Generated by Django 4.2.6 on 2023-11-16 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_tracker', '0006_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='first_name',
            field=models.CharField(default='Fname', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='last_name',
            field=models.CharField(default='Lname', max_length=200),
            preserve_default=False,
        ),
    ]
