# Generated by Django 4.2.6 on 2023-11-17 04:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('task_tracker', '0007_student_first_name_student_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='leaderGroup',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leader_group', to='auth.group'),
        ),
        migrations.AddField(
            model_name='department',
            name='memberGroup',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='member_group', to='auth.group'),
        ),
    ]
