# Generated by Django 4.2.6 on 2023-11-17 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_tracker', '0009_task_assignedstudents'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'permissions': (('manage_task', 'Manage task'),)},
        ),
    ]
