# Generated by Django 4.2.6 on 2023-11-17 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_tracker', '0010_alter_task_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'permissions': (('manage_department', 'Manage department'),)},
        ),
    ]
